[package]
name = "mkpydir"
version = "0.1.0"
edition = "2021"
description = "Quickly create a new Python directory with boilerplate code."
license = "MIT" # or the appropriate license

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
